### ISSUE TITLE
IE 11 Not working

### ISSUE THREAD

**Issue by renaco** [Mobius1/Vanilla-DataTables#1]
Hello there!

I try launch in IE11 but not working, appears all rows without controls.

Regards!

**Comment by Mobius1** [comment]
Thanks, I'll look into this.

**Comment by Mobius1** [comment]
IE bugs fixed in the latest version: https://github.com/Mobius1/Vanilla-DataTables/releases/tag/0.1.2

**Comment by renaco** [comment]
It works!
Nice job!
