### ISSUE TITLE
Getting multiple tables information of one table

### ISSUE THREAD

**Issue by OGKevin** [Mobius1/Vanilla-DataTables#10]
Hi,

Basically when i call a function to create a table, it creates it as it should, but when i recall the function on the same table with new data, instead of clearing the previous data and reload it with new one, i get a table with `i` search bars, prev and next pages and showing entries texts. So like a table inside another table ?

U can see it in action on may project --> https://combunqweb.herokuapp.com/manager/
press twice on `via CSV text` and u will see, right now the function looks like [this](https://github.com/OGKevin/ComBunqWebApp/blob/master/static/Manager/JS/index.js#L125). On my local branch I've implemented an if statement that will call `dataTable.refresh` if the table has already been made and this doesn't fix the issue. 

Is this indeed a bug or did i made a mistake on my end ?

**Comment by Mobius1** [comment]
Your `createTable()` function is re-initializing the plugin on the table whenever you press the button so there are duplicate containers.

**Comment by OGKevin** [comment]
yes, so the plug in itself doesn't have a function to prevent this action and to just 'refresh' when/if the table has already been made but the data is changing ?

**Comment by Mobius1** [comment]
When you initialise the plugin it wraps the table in the custom containers. If you try and initialise the plugin on the table again, it gets wrapped in duplicate containers - hence the duplicate elements you're getting.

You might need to do something like this:

```javascript
var dataTable;

function createTable(input) {
    var rows = [],
        headers = Object.keys(input[0]);

    for (var i = 0; i < input.length; i++) {
        rows.push(Object.keys(input[i]).map(function(key) {
            return input[i][key];
        }))
    }

    options = {
        data: {
            'headings': headers,
            "rows": rows
        }
    }

    // Check to see if initialized
    if ( dataTable ) {
        // Wipe the table
        dataTable.clear();

        // Destroy the containers
        dataTable.wrapper.parentNode.replaceChild(dataTable.table, dataTable.wrapper);
    }

    // Init
    dataTable = new DataTable("#transactionsInfo", options);

    $("#transactionsInfo").css('visibility', 'visible');
}
```

**Comment by OGKevin** [comment]
Thanks for this snippet! appreciate it. 👍
