### ISSUE TITLE
Export/Get shown entries

### ISSUE THREAD

**Issue by OGKevin** [Mobius1/Vanilla-DataTables#11]
Lets say i've a table that looks like one of your [demos](http://mobius.ovh/docs/vanilla-datatables/pages/demos). Would it be nice if after the data is presented in the table that one could do `datatable.export()` and it will export the current page and its entries? 

#### Usage example

First demo table. The user wants all employees that started on 03/03. He searches 03/03 in the search bar, the results returns and he wants to 'copy paste' it in its own administration. So he presses an 'export' button. Behind the sense in JS you would do `datatable.export()` gets the data and then I can transform this data and present it in a format that the user could/want to use like CSV maybe.

I would really like this feature and I'am prepared to implement it my self if you don't see a use for this. However i would need to be pointed in the right direction to achieve this.

**Comment by Mobius1** [comment]
Exporting data is on my todo list so I'll push it through quicker now it's been requested. Keep an eye out for the update 👍

**Comment by OGKevin** [comment]
Alright appreciate it! 💪

**Comment by OGKevin** [comment]
***Appreciate the update!***

However I've found a bug or I'm doing something wrong.

Look at this table:

![1](https://camo.githubusercontent.com/294f3e3425a2d3b15b77f39764b497a0d43339b6/687474703a2f2f692e696d6775722e636f6d2f4d5256674d7a6d2e706e67)

And the export code:

```javascript
$("#export").click(function(event) {
  /* Act on the event */
  if (dataTable) {
    dataTable.export('csv', 'test', ';')
  }else {
    console.log('Table not created');
  }
});
```

generates the following csv:

```csv
Payment ID;Account ID;Date;Ammount;Account IBAN;Payee IBAN;Name;Description;Type
19651;1837;2017-05-12 16:21:10.601136;-400;NL98BUNQ9900019091;NL06BUNQ9900029283;Guthrie Onderlinge Waarborgmaatschappij;;BUNQ
19649;1837;2017-05-12 16:20:55.626039;-600;NL98BUNQ9900019091;NL67BUNQ9900030222;Guthrie Onderlinge Waarborgmaatschappij;;BUNQ
19648;1837;2017-05-12 16:07:05.768396;10000;NL98BUNQ9900019091;NL91ABNA0417164300;Guthrie Onderlinge Waarborgmaatschappij;Topup account NL98BUNQ9900019091GuthrieOnderlingeWaarborgmaatschappij;IDEAL
19645;1837;2017-05-12 16:03:08.287890;-500;NL98BUNQ9900019091;NL41BUNQ9900029526;Guthrie Onderlinge Waarborgmaatschappij;Money;BUNQ
17363;1837;2017-04-17 11:01:06.646239;-11.05;NL98BUNQ9900019091;NL37BUNQ9900000013;Catrice (nickname);invoice 1563;BUNQ
14065;1837;2017-03-16 11:01:08.782273;-11;NL98BUNQ9900019091;NL28BUNQ9900000951;bunq;invoice 625;BUNQ
8842;1837;2016-03-15 01:02:45.828381;2500;NL98BUNQ9900019091;NL91ABNA0417164300;Guthrie Onderlinge Waarborgmaatschappij;Welcome to bunq! 
iDEAL transaction identifier code: bpvnevvq 1749965413473546;IDEAL

```

See how the last line of the csv is not right ? It belongs to the line above it. It should be like this:

```csv
8842;1837;2016-03-15 01:02:45.828381;2500;NL98BUNQ9900019091;NL91ABNA0417164300;Guthrie Onderlinge Waarborgmaatschappij;Welcome to bunq! iDEAL transaction identifier code: bpvnevvq 1749965413473546;IDEAL

```
Or could it be that between the `bunq!` and `iDEAL` there is a `\n`? 
Any tips on how to debug this ?

**Comment by OGKevin** [comment]
turns out i was doing something wrong indeed 🤦‍♂️ 

Thanks for this update Karl !
