### ISSUE TITLE
Search: Multi-word

### ISSUE THREAD

**Issue by bshouse** [Mobius1/Vanilla-DataTables#12]
Love it! Nice work.

I ran into trouble with the search and did a little work that I wanted to share. I wanted to be able to search for more than one word. So hacked up your function a little.  I would be happy to submit a pull request, but my Javascript skill is low, and I am sure you can do it better.

This code replaces the "util.each" on line 950 of v1.1.7:
```
//Prepare query data
		var terms = query.split(/(\s+)/).filter( function(e) { return e.trim().length > 0; } );
		var queryNoWhitespace = query.replace(/ /g,'');
		for(var x = 0 ; x < terms.length; x++) {
			terms[x] = terms[x].toLowerCase();
		}
		
		util.each(_.rows, function(idx, row) {
			var inArray = util.includes(_.searchData, row);
			// Cheat and get the row's textContent instead of searching each cell :P
			if (terms.length == 1 && util.includes(row.textContent.toLowerCase(), query) && !inArray) {
				_.searchData.push(row);
				
			} else if(util.includes(row.textContent.toLowerCase(), queryNoWhitespace) && !inArray) {
				// Ordered Match
				_.searchData.push(row);

			} else {
				// Word Match
				var match=true;
				var text = row.textContent.toLowerCase();
				for(var x = 0; x < terms.length; x++) {
					if(!util.includes(text, terms[x])) {
						match=false;
						break;
					}
				}
				if(match) {
					_.searchData.push(row);
				}
				
			}
		});
```

**Comment by c1coucou2piou** [comment]
Same request. This piece of code (also) does the trick :
```
util.each(_.rows, function(idx, row) {
	var inArray = util.includes(_.searchData, row);
			
	var doesQueryMatch = query.split (" ").reduce (function (bool, word) {
		return bool && util.includes(row.textContent.toLowerCase(), word);
	}, true);
			
	// Cheat and get the row's textContent instead of searching each cell :P
	if (doesQueryMatch && !inArray) {
		_.searchData.push(row);
	}
});
```

Hope this will help. Long live to DataTable !

**Comment by bshouse** [comment]
@c1coucou2piou Wow!  That is much more elegant.  

I will plug it in today and confirm it works as needed since you obviously know much more JS than I do.

Thank you.

**Comment by bshouse** [comment]
As I am sure you know, it works like a dream. Thank you.

I will now go read up on how you did it.

**Comment by Mobius1** [comment]
@c1coucou2piou - Go ahead and submit a pull request with your snippet if you want buddy 👍

**Comment by c1coucou2piou** [comment]
Hum... I'm a very fresh new user to Git...
So, I have to RTFM to learn how to use Git and then l'll  pull a proper request.

Glad to hlep

**Comment by bshouse** [comment]
That I can do. I will be sure to credit you.

**Comment by Mobius1** [comment]
Done. Feel free to reopen if needed.
