### ISSUE TITLE
_ is undefined

### ISSUE THREAD

**Issue by bhritch** [Mobius1/Vanilla-DataTables#14]
Hi would like to ask, i'm getting this error? I follow how in code pen though i used it in requirejs
![image](https://cloud.githubusercontent.com/assets/2568801/26191606/22cda2e4-3be1-11e7-94d5-14828c198a9d.png)

**Comment by Mobius1** [comment]
Are you using the latest version?

**Comment by bhritch** [comment]
yes 1.1.8

**Comment by Mobius1** [comment]
Are you using either underscore or lowdash in your project?

**Comment by bhritch** [comment]
Yes, I have both in my node_modules. Is it conflict with those? or dependencies?

**Comment by Mobius1** [comment]
Could be a conflict as Vanilla-DataTables uses `_` as an alias for `this`.

**Comment by bhritch** [comment]
Oh okay, Thanks for the info :+1:

**Comment by Mobius1** [comment]
I'll remove `_` as an alias in the next update just to be safe.
