### ISSUE TITLE
Data from array of objects

### ISSUE THREAD

**Issue by jonasscalar** [Mobius1/Vanilla-DataTables#19]
Super amazing good job with this. 

Hey, I use .net webapi and receive JSON data like:

[
    {
        "ID": "583",        
        "CITY": "NOVO HAMBURGO",
        "STATE": "RS"       
    },
    {
        "ID": "1843",        
        "CITY": "IVOTI",
        "STATE": "RS"      
    }
	......
]

Any suggestions for bind directly via API?

**Comment by Mobius1** [comment]
There's probably a more refined way to do it, but try this:

```javascript
var data = [
	{
		"ID": "583",
		"CITY": "NOVO HAMBURGO",
		"STATE": "RS"
	},
	{
		"ID": "1843",
		"CITY": "IVOTI",
		"STATE": "RS"
	}
];

var obj = {};

obj.headings = Object.keys(data[0]);
obj.rows = [];


for ( var i = 0; i < data.length; i++ ) {
	
	obj.rows[i] = [];
	
	for (var p in data[i]) {
		if( data[i].hasOwnProperty(p) ) {
			obj.rows[i].push(data[i][p]);
		} 
	} 
}
```

which spits out an object that the API can use:

```javascript
{
   headings : [
      "ID",
      "CITY",
      "STATE"
   ],
   rows : [
      [
         "583",
         "NOVO HAMBURGO",
         "RS"
      ],
      [
         "1843",
         "IVOTI",
         "RS"
      ]
   ]
}
```
