### ISSUE TITLE
Missing Refresh?

### ISSUE THREAD

**Issue by pandafinity** [Mobius1/Vanilla-DataTables#2]
Hi,

I love this table plugin (so thank you), but I am using the search function and cannot seem to get the table to 'refresh' if I clear the search input field with $('#id).val('').  I tried triggering a 'change' on the search field but it only seems to have a listener for 'keyup'.

Sorry if this is not an issue, but I can't see a way to reset the table content prior to search.

Thanks :)

**Comment by Mobius1** [comment]
The update() method is available to do that, but it was buggy so I've pushed a new version with a fix as well as adding a new method to refresh the table.

You can grab it here: [v0.1.3](https://github.com/Mobius1/Vanilla-DataTables/releases/tag/0.1.3) then:

```javascript
// init
var dataTable = new DataTable(myTable);

// refresh the table
dataTable.refresh();
```

**Comment by pandafinity** [comment]
Hi :)

Thanks for the quick response, it worked brilliantly so thank you.

I noticed in the fix file 'vanilla-dataTables.js' you seem to have a pasting error as you have this at the bottom:

```
	return Plugin;
}));update(e);
			_this.trigger('datatable.sort');
		},
		clear: function()
		{
			if ( this.table.tBodies.length ) {
				// IE doesn't play nice with innerHTML on tBodies.
				if ( this.isIE ) {
					while(this.tbody.hasChildNodes()) {
						this.tbody.removeChild(this.tbody.firstChild);
					}
				} else {
					this.tbody.innerHTML = '';
				}
			}
		},
	};
	return Plugin;
}));
```
I removed the duplicate ending and it run without errors.  Not sure if you noticed it so wanted to say in case not.

Thanks again for your help and quick reply

Enjoy your week :)

**Comment by Mobius1** [comment]
Good catch, thanks! Updated :)
