### ISSUE TITLE
preventDefault stops anchors working in tables v1.3.0 onwards

### ISSUE THREAD

**Issue by spriggsey** [Mobius1/Vanilla-DataTables#23]
Originally started using this on version 1.2.4 which allowed anchors to work natively in tables but moving to 1.3.0 onwards, a preventDefault has now started to affect all anchors from within the table and requires manual override to avoid it.

https://github.com/Mobius1/Vanilla-DataTables/blob/d8fa162bd4f838323346c01781f922fd98fb3352/src/vanilla-dataTables.js#L1292-L1303

Is there any quick solution to this problem or would I require to set my own event to override the original preventDefault?

**Comment by Mobius1** [comment]
I'll get a fix out ASAP.

**Comment by Mobius1** [comment]
This should be fixed in [1.3.3](https://github.com/Mobius1/Vanilla-DataTables/releases/tag/1.3.3). Re-open if needed.
