### ISSUE TITLE
Export option doesn't export all the columns

### ISSUE THREAD

**Issue by bshowy2k** [Mobius1/Vanilla-DataTables#25]
I have an object with around 20 columns but when I load it into the table I just show the first 3 column for a better user experience and the other 17 rows I keep them hide, so far so good but when I show any of the rest of the column and try to export the table, the exported file only contains the first 3 columns and the others doesn't get exported.

**Comment by Mobius1** [comment]
This is fixed in the latest release. Re-open if needed.
