### ISSUE TITLE
Hot to render a button/image/hyperlink column?

### ISSUE THREAD

**Issue by richardsonvix** [Mobius1/Vanilla-DataTables#27]
How to render a button/image/hyperlink to a specific column by delegating a function?

 I need put a clickable column to open an URL.

**Comment by ndtreviv** [comment]
If you're building the table and then initializing the DataTable you can just set the contents of the cell to be the link you want.

However, +1 for the option of `formatter` being a function that formatting can be delegated to.

**Comment by Mobius1** [comment]
Cell formatting / rendering is definitely something that needs to be added.

**Comment by Mobius1** [comment]
A custom column renderer can now be used. See the [columns](https://github.com/Mobius1/Vanilla-DataTables/wiki/columns#render) option.

**Comment by richardsonvix** [comment]
Excellent news @Mobius1 !!!

Thank you.

**Comment by Mobius1** [comment]
Closing this now. Reopen if any issues arise.
