### ISSUE TITLE
Incomplete json import 

### ISSUE THREAD

**Issue by saltcod** [Mobius1/Vanilla-DataTables#29]
ohai! 

Got a weird issue. Only some of the json data gets added to my table. Weird! 

json file is here: https://github.com/saltcod/overcast/blob/master/assets/js/overcast.json

All of the data was imported properly a few weeks back when I was working on this, but now I get this situation happening. Not sure what happened in the meantime. Appreciate any suggestions! 

https://dl.dropboxusercontent.com/s/fy73b53klgleja6/2017-09-08%20at%2010.19%20PM.png

Thanks!

**Comment by Mobius1** [comment]
Hmmm, looks like something got tweaked during an update. I can reproduce it so I'll get it fixed quickly.

**Comment by Mobius1** [comment]
This should be fixed in the latest [version](https://github.com/Mobius1/Vanilla-DataTables/releases/tag/1.4.16). Re-open if needed.

**Comment by saltcod** [comment]
Woah!  Ultra quick!!

Yep this fixes the issue. 

Many, many thanks for the really quick reply.  Greatly appreciate that, and the plugin itself. Fantastic work!
