### ISSUE TITLE
Rendering takes nearly 30 seconds

### ISSUE THREAD

**Issue by pandafinity** [Mobius1/Vanilla-DataTables#3]
Hi,

I hope you're well and enjoying your week.  I wanted to write as I am using and loving your Vanilla-DataTables plugin.  

The problem I am having is that I am returning 164 'rows' from the database and the plugin is taking nearly 30 seconds to Render the table.  This is 95% of the total time.  But this can be split further - 92% of the 30 seconds is used to 'recalculate' the style.

This seems way too slow, so I wanted to ask if this was an issue or something that people have come across before, or if I can look at some area which may help me understand why it's so slow?

I am using version 1.3 - so not sure if the difference between this and 1.4 has performance updates.

Any information you might be able to provide would be greatly appreciated.

Thanks again :)

**Comment by Mobius1** [comment]
Hiya.

Wow, that's a serious problem. What browser are you using?

The only performance hits I ran into during testing was with a 10000 row table during sorting. There's a demo here with a 1000 rows which renders quite fast without problems: http://s.codepen.io/Mobius1/debug/NdmgJJ.

**Comment by pandafinity** [comment]
Thanks for coming back so quickly.  I need to check this out - it's very quick on my machine, it's when I upload to the server that it takes so long. Mmm...

The table is rendered in HTML (from a pug template) and the :

`var dataTable = new DataTable(propertyTable, options);`

is called in Document.ready.

I am using Chrome browser, but I have no issues locally, so not sure where to start if I am honest.
I guess my issues is with what I'm doing and not your great plugin.

The row has 'material icons' in some of the td cells, along with info from a mongodb - Works quickly on my local machine - so I need to try and see how to trace what it is doing while re-rendering.

Thanks again for coming back to me and helping.

:)

**Comment by Mobius1** [comment]
Strange. Let me know how it goes.

I'll leave this open if you need any further help and just in case anyone else has the same problem.

**Comment by Mobius1** [comment]
I'm going to close this for now. Feel free to reopen at any time.

**Comment by pandafinity** [comment]
Hi,
Sorry, life took over.  I have a feeling that because I am rendering a pug template that takes data from a db and then rendering each table row based on the data and some added logic it may recalculate each row more than once.
Sorry I didn't get back to you.  I won't be able to look at this for a couple of weeks.

Thanks again.
