### ISSUE TITLE
Can't dynamically add row.

### ISSUE THREAD

**Issue by scott20145** [Mobius1/Vanilla-DataTables#33]
I tried to add row using the API, but the row data can't show up. 
It will just render `Showing 1 to 1 of 1 entries`.

Below is my code:
```javascript 
    var table = new DataTable('#table', {
        searchable: false,
        data: {
            headings: [
                "date",
                "ype",
                "gane",
                "total",
                "result"
            ],
            rows: [
            ]
        }
    });
    table.rows().add(['2017-07-30', '55', '11', '46.40', '-48.7']);
```

**Comment by Mobius1** [comment]
The bug has ben fixed in the latest version.

Note that the `rows` property has been changed to `data`, but the wiki didn't get updated for some reason - see [data](https://github.com/Mobius1/Vanilla-DataTables/wiki/data). Sorry about that.
