### ISSUE TITLE
No luck using inside TypeScript

### ISSUE THREAD

**Issue by ministrycrm** [Mobius1/Vanilla-DataTables#34]
I am trying to pull library into my TypeScript application like this:

`const DataTable = require('vanilla-datatables');`

I am getting an error on pageload:
`Uncaught TypeError: Cannot read property 'tagName' of undefined at Object.DataTable (vanilla-dataTables.js:965)`

Thinking that just including this script is trying to init DataTables, when debugging "table" is undefined here: 
`var DataTable = function (table, options) {`

When I include vanilla-datatables with the CDN link in my EJS file everything works fine.

**Comment by Mobius1** [comment]
See if the error still occurs with the latest version (1.6.7).

**Comment by ministrycrm** [comment]
The error changed now:
```
Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at Object.DataTable (vanilla-dataTables.js:960)
```

**Comment by ziafal86** [comment]
Hi, this fix should help

    (function (factory) {
        "use strict";
        var plugin = "DataTable";

        if ( typeof define === 'function' && define.amd ) {
            // AMD
            define( [], function () {
                    return factory( plugin );
            } );
        }
        else if ( typeof exports === 'object' ) {
            // CommonJS
            module.exports = function () {
                    return factory( plugin );
            };
        }
        else {
            // Browser
            factory( plugin );
        }
    }
    (function (plugin) {
        // start old plugin content
        "use strict";
        ...
        return DataTable;
        // end old plugin content
    }));

**Comment by ministrycrm** [comment]
Works great now with webpack
