### ISSUE TITLE
add dataTables-empty class to dataTable-wrapper element instead of td

### ISSUE THREAD

**Issue by henser** [Mobius1/Vanilla-DataTables#54]
This is just a suggestion for a more ideal classification of elements inside the datatable markup. Will leave it for author's consideration.
It feels much more useful to have a dataTables-empty class assigned to the dataTable-wrapper element rather than in an empty table cell. This way it would be possible to manipulate the style of all the elements when a table is empty by using CSS only.

**Comment by Mobius1** [comment]
Good idea. I'll push this in the next update.

**Comment by Mobius1** [comment]
This has been implemented in [`v1.6.13`](https://github.com/Mobius1/Vanilla-DataTables/commit/5c7552380efb72ad5b3b03fd4319dd824dab3760)
