### ISSUE TITLE
version to target

### ISSUE THREAD

**Issue by johanneswilm** [Mobius1/Vanilla-DataTables#55]
Hey,
at Fidus Writer we have been using jQuery Datatables for many years. Now 'd like to move to a vanilla alternative. This looks great, but looking at the commit history, I don't quite understand whether version 1.6, 2.0 are best targets for something that is to be launched in a few months time. This also because we'll likely shortly need to target mobile users as well so we'd need to create a responsive plugin of some kind.

**Comment by Mobius1** [comment]
The v2 branch is stull under development so it's not guaranteed to be stable. I've not had much time recently, but I've now got the time to continue active development of the v2 branch.

**Comment by johanneswilm** [comment]
@Mobius1 Ok, got it. Currently we are working with my patch to your v1 branch and there seem not to be any more relevant bugs, but before release it would be good to switch to a release version.
