### ISSUE TITLE
feat-requ/quiestion : put aside of the rows per page the index paginatio and total rows?

### ISSUE THREAD

**Issue by mckaygerhard** [Mobius1/Vanilla-DataTables#6]
again me, after the selectr and the vanilla datatable i'm again with things:

1) EASE HOW CAN I ALSO PUT "showing XX of $$ rows" aside of the "dataTable-selector"-dataTable-selectWrapper" rows per page combobox?

2) EASE HOW CAN I ALSO PUT PAGINATION pages index aside of the of the "dataTable-selector"-dataTable-selectWrapper" rows per page combobox? 

3) CAN BE MADE that both or at lease tell me how to move it!

**Comment by mckaygerhard** [comment]
thanks for the feature of search without heading, now please some way to do that of put idex pagination on header "too"?

**Comment by Mobius1** [comment]
In order to have two pagers you'd have to clone the current one, append it to the top container, allow it to control the table and update it when required:

```javascript
// Initialise
var dataTable = new DataTable(table, options);

var topContainer = dataTable.container.parentNode.firstElementChild;
var topPager = dataTable.paginator.parentNode.cloneNode(true);

// Append the new pager
topContainer.appendChild(topPager);

// Enable the new pager
topContainer.addEventListener("click", function(e) {
	var target = e.target;
	
	if ( target.nodeName === "A" && target.hasAttribute("data-page") ) {
		var page = target.getAttribute("data-page");
		dataTable.page(page);
	}
});

// Update the new pager
dataTable.on("datatable.update", updatePager);
dataTable.on("datatable.page", updatePager);

function updatePager() {
	topContainer.replaceChild(dataTable.paginator.parentNode.cloneNode(true), topContainer.lastElementChild);
}
```

**Comment by mckaygerhard** [comment]
well its rendered, but now i have a little problem, when i click on any page of the index pagination on top, only the botton indice are updated, i mean the bottom part if i click on "7" the numbers change to 4567890 with 7 selected, but in the top, remains with no updates..

**Comment by mckaygerhard** [comment]
UPDATE: i got in console:

```
Uncaught TypeError: Cannot read property 'nodeName' of undefined 127.0.0.1/:231
(anonymous function)
```

on the line:
`if ( target.nodeName === "A" && target.hasAttribute("data-page") ) {`

**Comment by mckaygerhard** [comment]
UPDATE got working but not refresh top pager:

i got working when click on the top pagination index number, and goes to the respective page, but now the number not change, always show "1" only changes the number of the bottom bager..

**Comment by mckaygerhard** [comment]
hey, men, w'up, still not got working this trick.. i got the pagination index on top and when click goes to the page and rows display correctly but the number are not marks bold, still persist "1! on bold, the botton pager works normal

**Comment by Mobius1** [comment]
Can you post your code so I can see what's going on?

**Comment by mckaygerhard** [comment]
here a complete code of table tag and js tag, when ai click the numbers of the top index work but number clicked does not marks bold, all the rest works as expected:

```
-------<br><table border="0" cellpadding="1" cellspacing="0" vanilladatatable=0  id="table360">
<thead>
<tr>
<th>col1: </th><th>col2</th></tr>
</thead>
<tbody>
<tr>
<td>celda tabla: </td><td>otra c<br>awefwerfqwefqwefelsa2</td></tr>
<tr>
<td>celda tab<br>awefwerfqwefqwefla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tablawqefqewfqew<br>awefwerfqwefqwef: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tabla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tab<br>awefwerfqwefqwefla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tablawqefqewfqew<br>awefwerfqwefqwef: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tabla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tab<br>awefwerfqwefqwefla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tablawqefqewfqew<br>awefwerfqwefqwef: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tabla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tab<br>awefwerfqwefqwefla: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tablawqefqewfqew<br>awefwerfqwefqwef: </td><td>otra celsa2</td></tr>
<tr>
<td>celda tabla: </td><td>otra celsa2</td></tr>
</tbody>
</table><script src="http://127.0.0.1/~systemas/appweb/scripts/vanilla-dataTables.js"></script>
						<script>
						var tabletable360 = document.getElementById('table360');
						var optionstable360 = {  sortable: true, searchable: true, perPage: 5 };
						var datatable360 = new DataTable(tabletable360, optionstable360);
						// top paginator custom render
						var topContainer = datatable360.container.parentNode.firstElementChild;
						var topPager = datatable360.paginator.parentNode.cloneNode(true);
						// Append the new pager
						topContainer.appendChild(topPager);
						// Enable the new pager
						topContainer.addEventListener("click", function(e) {
							var target = e.target;
							if ( target.nodeName.toLowerCase() === 'a' && target.hasAttribute("data-page") ) {
									var page = target.getAttribute("data-page");
									datatable360.page(page);
								}	}	);
						// Update the new pager
						datatable360.on("datatable360.update", updatePager);
						datatable360.on("datatable360.page", updatePager);
						// define hack function to update when click new pager
							function updatePager() 
							{
								topContainer.replaceChild(datatable360.paginator.parentNode.cloneNode(true), topContainer.lastElementChild);
							}
						</script>

```

**Comment by Mobius1** [comment]
I can see the problem. The `event type` is wrong:

```javascript
	datatable360.on("datatable360.update", updatePager);
	datatable360.on("datatable360.page", updatePager);
```
should be:
```javascript
	datatable360.on("datatable.update", updatePager);
	datatable360.on("datatable.page", updatePager);
```

## [Events](http://mobius.ovh/docs/vanilla-datatables/pages/events)

**Comment by mckaygerhard** [comment]
i must pay more attention to the documentaion (its due i really hate all of javascript related) GREAT! THANKS!

**Comment by mckaygerhard** [comment]
hey hey waith.. when i have two datbles, ? how? i click the button in the first table and only the second table event are working

**Comment by mckaygerhard** [comment]
solved! the names of the function to update the objects must be differents ( topContainer, topPager and updatePager)

**Comment by Mobius1** [comment]
Just to let you know that the latest version allows you to customize the layout as well as use multiple pagers without the above hack. See [docs](http://mobius.ovh/docs/vanilla-datatables/pages/layout)

**Comment by mckaygerhard** [comment]
do u really update and improve the ocumentation! good job!
